//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Test
{
    using System;
    using System.Collections.Generic;
    
    public partial class Demo_12_21_2012
    {
        public int stateCode { get; set; }
        public short data_year { get; set; }
        public byte data_month { get; set; }
        public Nullable<decimal> PCP { get; set; }
        public Nullable<int> CDD { get; set; }
        public Nullable<int> HDD { get; set; }
        public Nullable<decimal> TAVG { get; set; }
        public Nullable<decimal> TMIN { get; set; }
        public Nullable<decimal> TMAX { get; set; }
    }
}
